yTraceback (most recent call last):
  File "/workspace/table-to-text-flan-t5/fine_tune_gemma_1b.py", line 10, in <module>

�    from transformers import  AutoTokenizer, AutoModelForCausalLM, Trainer, TrainingArguments, DataCollatorWithPadding
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2317, in __getattr__

�    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2347, in _get_module

{    raise e
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2345, in _get_module

I    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/tokenization_auto.py", line 40, in <module>

�    from .auto_factory import _LazyAutoMapping
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 43, in <module>

�    from ...generation import GenerationMixin
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2317, in __getattr__

�    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2347, in _get_module

{    raise e
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2345, in _get_module

�    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module

�    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 120, in <module>

�    from accelerate.hooks import AlignDevicesHook, add_hook_to_module
  File "/usr/local/lib/python3.10/dist-packages/accelerate/__init__.py", line 16, in <module>

�    from .accelerator import Accelerator
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 36, in <module>

�    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/usr/local/lib/python3.10/dist-packages/accelerate/checkpointing.py", line 24, in <module>

~    from .utils import (
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/__init__.py", line 190, in <module>

�    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/bnb.py", line 29, in <module>

�    from ..big_modeling import dispatch_model, init_empty_weights
  File "/usr/local/lib/python3.10/dist-packages/accelerate/big_modeling.py", line 24, in <module>

t    from .hooks import (
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 30, in <module>

�    from .utils.other import recursive_getattr
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/other.py", line 36, in <module>

�    from .transformer_engine import convert_model
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/transformer_engine.py", line 21, in <module>

�    import transformer_engine.pytorch as te
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/__init__.py", line 6, in <module>

�    from .module import LayerNormLinear
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/module/__init__.py", line 6, in <module>

�    from .layernorm_linear import LayerNormLinear
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/module/layernorm_linear.py", line 15, in <module>

�    from .. import cpp_extensions as tex
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/cpp_extensions/__init__.py", line 6, in <module>

:    from transformer_engine_extensions import *
ImportError: /usr/local/lib/python3.10/dist-packages/transformer_engine_extensions.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
