�ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch-tensorrt 2.0.0.dev0 requires torch<2.2,>=2.1.dev, but you have torch 2.8.0 which is incompatible.
torchdata 0.7.0a0 requires torch==2.1.0a0+29c30b1, but you have torch 2.8.0 which is incompatible.
torchtext 0.16.0a0 requires torch==2.1.0a0+29c30b1, but you have torch 2.8.0 which is incompatible.

�Successfully installed accelerate-0.30.1 bitsandbytes-0.43.3 colorama-0.4.6 datasets-2.19.0 dill-0.3.8 evaluate-0.4.3 hf-xet-1.1.10 huggingface-hub-0.35.3 lxml-6.0.2 multiprocess-0.70.16 nltk-3.9.2 numpy-1.24.4 nvidia-cublas-cu12-12.8.4.1 nvidia-cuda-cupti-cu12-12.8.90 nvidia-cuda-nvrtc-cu12-12.8.93 nvidia-cuda-runtime-cu12-12.8.90 nvidia-cudnn-cu12-9.10.2.21 nvidia-cufft-cu12-11.3.3.83 nvidia-cufile-cu12-1.13.1.3 nvidia-curand-cu12-10.3.9.90 nvidia-cusolver-cu12-11.7.3.90 nvidia-cusparse-cu12-12.5.8.93 nvidia-cusparselt-cu12-0.7.1 nvidia-nccl-cu12-2.27.3 nvidia-nvjitlink-cu12-12.8.93 nvidia-nvtx-cu12-12.8.90 peft-0.10.0 portalocker-3.2.0 pyarrow-21.0.0 pyarrow-hotfix-0.7 rouge-score-0.1.2 sacrebleu-2.5.1 safetensors-0.6.2 scikit-learn-1.3.2 scipy-1.10.1 sentencepiece-0.2.0 soxr-1.0.0 sympy-1.14.0 tokenizers-0.22.1 torch-2.8.0 torchaudio-2.8.0 torchvision-0.23.0 transformers-4.57.0 triton-3.4.0 typing-extensions-4.15.0 xxhash-3.6.0

�WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

y
[notice] A new release of pip is available: 23.2.1 -> 25.2
[notice] To update, run: python -m pip install --upgrade pip

?Found existing installation: transformer-engine 0.11.0+3f01b4f

0Uninstalling transformer-engine-0.11.0+3f01b4f:

=  Successfully uninstalled transformer-engine-0.11.0+3f01b4f

�WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

�Could not find the bitsandbytes CUDA binary at PosixPath('/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda128_nocublaslt.so')

�The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.

�Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2317, in __getattr__

�    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2347, in _get_module

{    raise e
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2345, in _get_module

�    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module

�    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import

�  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked

D  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

J  File "<frozen importlib._bootstrap_external>", line 883, in exec_module

�  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 220, in <module>

w    from peft import PeftModel
  File "/usr/local/lib/python3.10/dist-packages/peft/__init__.py", line 22, in <module>

l    from .auto import (
  File "/usr/local/lib/python3.10/dist-packages/peft/auto.py", line 31, in <module>

y    from .config import PeftConfig
  File "/usr/local/lib/python3.10/dist-packages/peft/config.py", line 23, in <module>

�    from .utils import CONFIG_NAME, PeftType, TaskType
  File "/usr/local/lib/python3.10/dist-packages/peft/utils/__init__.py", line 21, in <module>

�    from .loftq_utils import replace_lora_weights_loftq
  File "/usr/local/lib/python3.10/dist-packages/peft/utils/loftq_utils.py", line 35, in <module>

    import bitsandbytes as bnb
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/__init__.py", line 15, in <module>

    from .nn import modules
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/nn/__init__.py", line 17, in <module>

�    from .triton_based_modules import (
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/nn/triton_based_modules.py", line 7, in <module>

�    from bitsandbytes.triton.int8_matmul_mixed_dequantize import (
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/triton/int8_matmul_mixed_dequantize.py", line 12, in <module>

G    from triton.ops.matmul_perf_model import early_config_prune, estimate_matmul_time
ModuleNotFoundError: No module named 'triton.ops'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/table-to-text-flan-t5/fine_tune_gemma_1b.py", line 8, in <module>

�    from transformers import (
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2320, in __getattr__

�    raise ModuleNotFoundError(
ModuleNotFoundError: Could not import module 'Trainer'. Are this object's requirements defined correctly?

removing /jobs/275632

Failed to execute script
